#!/usr/bin/env php
<?php
use wapmorgan\Threadable\Worker;
use wapmorgan\Threadable\WorkersPool;
require_once __DIR__.'/../vendor/autoload.php';

class SimpleWorkerWithVariableDelay extends Worker
{
    public function onPayload($payload)
    {
        echo 'Sleeping for '.$payload['seconds'].' sec'.PHP_EOL;
        sleep($payload['seconds']);
        echo 'Waking up'.PHP_EOL;
    }
}

$pool = new WorkersPool('SimpleWorkerWithVariableDelay');
$pool->setPoolSize(4);
$pool->enableDataOverhead();

for ($i = 0; $i < 9; $i++)
    $pool->sendData(['seconds' => rand(2, 5)]);

var_dump($pool->getWorkers());

$pool->waitToFinish([
    '0.5' => function (WorkersPool $pool) {
        echo 'Microtime: '.microtime(true)."\t".'Running threads: '.$pool->countRunningWorkers().PHP_EOL;
    }
]);
